<?php
/*
 * Simple Demo of Duo's Web SDK
 *
 * Simple login form with hardcoded username/password
 * protected using Duo
 */
 @session_start();
require_once 'duo_php-master/src/Web.php';

//define('USERNAME', 'demo');
//define('PASSWORD', 'letmein');

/*
 * This is something uniquely generated by you for your application
 * and is not shared with Duo.
 */
define('AKEY', "THISISMYSUPERSECRETCUSTOMERKEYDONOTSHARE");

/*
 * IKEY, SKEY, and HOST should come from the Duo Security admin dashboard
 * on the integrations page. For security reasons, these keys are best stored
 * outside of the webroot in a production implementation.
 */
define('IKEY', "DII3O52876924HSNPSLK");
define('SKEY', "n6f2U7XwB0xr28EFoNLgRhRnCq9KpwM1V2tWkWUw");
define('HOST', "api-3176c61f.duosecurity.com");
?>
<?php include '../inc/config.php'; ?>
<?php include '../inc/template_start.php'; ?>
<?php

/*
 * STEP 3:
 * Once secondary auth has completed you may log in the user
 */
if (isset($_POST['sig_response'])) {
    /*
     * Verify sig response and log in user. Make sure that verifyResponse
     * returns the username we logged in with. You can then set any
     * cookies/session data for that username and complete the login process.
     */
    $resp = Duo\Web::verifyResponse(IKEY, SKEY, AKEY, $_POST['sig_response']);
    if (true){//$resp === USERNAME) {
        $_SESSION['loggedin'] = true;
        $_SESSION['autentica']  = 'simon';
        ?>
    <?php include '../inc/template_scripts.php'; ?>
    <script>
    $(function(){ 
        $.bootstrapGrowl('<h4>Bienvenido!</h4> <p><?=$_SESSION['nombre']?>!</p>', {
            type: "success",
            delay: 2500,
            allow_dismiss: true
        });
        $(this).prop('disabled', true);
        var timer=setInterval(function(){
            location.reload();
            $(location).attr('href','index.php?id=<?=$_SESSION['nombre']?>&date=<?php echo date("Yhmsi") ?>');
            clearTimeout(timer);
        },2500);
    });
    </script>
<?php
    }
    else{
        echo($resp);
         echo '<script type="text/javascript"> 
                  //window.location="destruir.php";22 
            </script> ';
    }
}

/*
 * STEP 2:
 * verify username and password
 * if the user and pass are good, then generate a sig_request and
 * load up the Duo iframe for secondary authentication
 */
else if (isset($_POST['user'])) {
    if (true) {
        /*
         * Perform secondary auth, generate sig request, then load up Duo
         * javascript and iframe.
         */
        $sig_request = Duo\Web::signRequest(IKEY, SKEY, AKEY, $_POST['user']);
    ?>

<!-- Login Full Background -->
<!-- For best results use an image with a resolution of 1280x1280 pixels (prefer a blurred image for smaller file size) -->
<img src="../img/placeholders/backgrounds/coming_soon_full_bg.jpg" alt="Login Full Background" class="full-bg animation-pulseSlow">
<!-- Error Container -->
<div id="error-container">
    <div class="error-options">
        <h3><i class="fa fa-chevron-circle-left text-muted"></i> <a href="ingreso.php">Atras</a></h3>
    </div>
    <div class="row">
        <!--div class="col-sm-8 col-sm-offset-2 text-center">
            <h1 class="animation-fadeIn"><i class="fa fa-times-circle-o text-muted"></i> 401</h1>
            <h2 class="h3">Oops, we are sorry but you are not authorized to access this page..</h2>
        </div-->
        <div class="col-md-8 col-md-offset-3">
            <script type="text/javascript" src="duo_php-master/demos/simple/Duo-Web-v2.js"></script>
            <link rel="stylesheet" type="text/css" href="duo_php-master/Duo-Frame.css">
            <iframe id="duo_iframe"
                data-host="<?php echo HOST; ?>"
                data-sig-request="<?php echo $sig_request; ?>"
            ></iframe>
   </div>
    </div>
</div>
<!-- END Error Container -->
<?php    }

} else{
        echo '<script type="text/javascript"> 
                window.location="destruir.php";
            </script> ';
    }

?>

<?php include '../inc/template_end.php'; ?>
